version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
    networks:
      - flytrack-network
    depends_on:
      - backend

  backend:
    image: aerosmart-backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - flytrack-network

networks:
  flytrack-network:
    driver: bridge
